// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const srLatn: any = {
  locale: "sr-Latn",
  socialButtonsBlockButton: "Nastavi sa {{provider|titleize}}",
  dividerText: "ili",
  formFieldLabel__emailAddress: "Email adresa",
  formFieldLabel__emailAddress_phoneNumber: "Email adresa ili broj telefona",
  formFieldLabel__phoneNumber: "Broj telefona",
  formFieldLabel__username: "Korisničko ime",
  formFieldLabel__firstName: "Ime",
  formFieldLabel__lastName: "Prezime",
  formFieldLabel__password: "Lozinka",
  formFieldLabel__newPassword: "Nova lozinka",
  formFieldLabel__confirmPassword: "Potvrdite lozinku",
  formFieldLabel__currentPassword: "Trenutna lozinka",
  formFieldLabel__backupCode: "Rezervni kod",
  formFieldInputPlaceholder__emailAddress: "vase@email.com",
  formFieldInputPlaceholder__emailAddress_phoneNumber: "vase@email.com ili +38160...",
  formFieldInputPlaceholder__password: "Unesite lozinku",
  formFieldInputPlaceholder__username: "korisnicko.ime",
  formFieldInputPlaceholder__firstName: "Ime",
  formFieldInputPlaceholder__lastName: "Prezime",
  formButtonPrimary: "Nastavi",
  signInEnterPasswordTitle: "Unesite lozinku",
  backButton: "Nazad",
  footerActionLink__useAnotherMethod: "Koristite drugi način",
  badge__primary: "Osnovno",
  badge__thisDevice: "Ovaj uređaj",
  badge__userDevice: "Korisnikov uređaj",
  badge__otherImpersonatorDevice: "Drugi uređaj",
  badge__default: "Podrazumijevano",
  badge__unverified: "Nepotvrđeno",
  badge__requiresAction: "Potrebna akcija",
  badge__you: "Vi",
  footerPageLink__help: "Pomoć",
  footerPageLink__privacy: "Privatnost",
  footerPageLink__terms: "Uslovi",
  paginationButton__previous: "Prethodno",
  paginationButton__next: "Sljedeće",
  paginationRowText__displaying: "Prikazuje se",
  paginationRowText__of: "od",
  membershipRole__guestMember: "Gost",
  membershipRole__basicMember: "Član",
  membershipRole__admin: "Administrator",

  signUp: {
    start: {
      title: "Kreirajte nalog",
      subtitle: "Dobrodošli u {{applicationName}}",
      actionText: "Već imate nalog?",
      actionLink: "Prijavite se",
    },
    emailLink: {
      title: "Potvrdite email",
      subtitle: "da biste nastavili u {{applicationName}}",
      formTitle: "Link za potvrdu",
      formSubtitle: "Koristite link poslan na vašu email adresu",
      resendButton: "Pošalji ponovo",
      verified: {
        title: "Uspješno ste se registrovali",
      },
      loading: {
        title: "Registracija u toku...",
      },
      verifiedSwitchTab: {
        title: "Email potvrđen",
        subtitle: "Vratite se na prvu karticu da nastavite",
        subtitleNewTab: "Otvorite novu karticu da nastavite",
      },
    },
    emailCode: {
      title: "Potvrdite email",
      subtitle: "da biste nastavili u {{applicationName}}",
      formTitle: "Kod za potvrdu",
      formSubtitle: "Unesite kod poslan na vašu email adresu",
      resendButton: "Pošalji ponovo",
    },
    phoneCode: {
      title: "Potvrdite broj telefona",
      subtitle: "da biste nastavili u {{applicationName}}",
      formTitle: "Kod za potvrdu",
      formSubtitle: "Unesite kod poslan na vaš telefon",
      resendButton: "Pošalji ponovo",
    },
    continue: {
      title: "Dopunite profil",
      subtitle: "da biste nastavili u {{applicationName}}",
      actionText: "Već imate nalog?",
      actionLink: "Prijavite se",
    },
    missingRequirements: {
      title: "Nedostaju podaci",
      subtitle: "da biste nastavili u {{applicationName}}",
      actionText: "Već imate nalog?",
      actionLink: "Prijavite se",
    },
  },

  signIn: {
    start: {
      title: "Prijavite se",
      subtitle: "Dobrodošli nazad u {{applicationName}}",
      actionText: "Nemate nalog?",
      actionLink: "Registrujte se",
      actionLink__use_email: "Koristite email",
      actionLink__use_phone: "Koristite telefon",
      actionLink__use_username: "Koristite korisničko ime",
      actionLink__use_email_username: "Koristite email ili korisničko ime",
    },
    password: {
      title: "Unesite lozinku",
      subtitle: "Dobrodošli nazad, {{firstName}}",
      actionLink: "Zaboravili ste lozinku?",
    },
    forgotPasswordAlternativeMethods: {
      title: "Zaboravili ste lozinku?",
      label__alternativeMethods: "Ili se prijavite na drugi način",
    },
    forgotPassword: {
      title: "Resetujte lozinku",
      subtitle: "za {{applicationName}}",
    },
    resetPassword: {
      title: "Postavite novu lozinku",
      actionLink: "Prijavite se",
      formButtonPrimary: "Nastavi",
    },
    resetPasswordMfa: {
      title: "Potvrdite identitet",
      subtitle: "da biste resetovali lozinku",
    },
    emailCode: {
      title: "Potvrdite email",
      subtitle: "Dobrodošli nazad, {{firstName}}",
      formTitle: "Kod za potvrdu",
      formSubtitle: "Unesite kod poslan na vašu email adresu",
      resendButton: "Pošalji ponovo",
    },
    emailLink: {
      title: "Potvrdite email",
      subtitle: "Dobrodošli nazad, {{firstName}}",
      formTitle: "Link za potvrdu",
      formSubtitle: "Koristite link poslan na vašu email adresu",
      resendButton: "Pošalji ponovo",
      loading: {
        title: "Prijava u toku...",
      },
      verifiedSwitchTab: {
        title: "Uspješno ste se prijavili",
        subtitle: "Vratite se na prvu karticu",
        subtitleNewTab: "Otvorite novu karticu",
      },
      verified: {
        title: "Uspješno ste se prijavili",
      },
    },
    phoneCode: {
      title: "Potvrdite telefon",
      subtitle: "Dobrodošli nazad, {{firstName}}",
      formTitle: "Kod za potvrdu",
      formSubtitle: "Unesite kod poslan na vaš telefon",
      resendButton: "Pošalji ponovo",
    },
    phoneCode_smsCode: {
      title: "Dvostepena provjera",
      subtitle: "da biste nastavili u {{applicationName}}",
      formTitle: "Kod za potvrdu",
      formSubtitle: "Unesite kod poslan na vaš telefon",
      resendButton: "Pošalji ponovo",
    },
    totpMfa: {
      title: "Dvostepena provjera",
      subtitle: "da biste nastavili u {{applicationName}}",
      formTitle: "Kod za potvrdu",
      formSubtitle: "Unesite kod iz aplikacije za autentifikaciju",
    },
    backupCodeMfa: {
      title: "Unesite rezervni kod",
      subtitle: "da biste nastavili u {{applicationName}}",
      formTitle: "Rezervni kod",
    },
    noAvailableMethods: {
      title: "Nije moguća prijava",
      subtitle: "Desila se greška",
      message: "Nije moguće prijaviti se — nema dostupnih načina prijave.",
    },
  },

  userButton: {
    action__manageAccount: "Upravljanje nalogom",
    action__signOut: "Odjava",
    action__signOutAll: "Odjava sa svih uređaja",
    action__addAccount: "Dodaj nalog",
  },

  userProfile: {
    navbar: {
      title: "Profil",
      description: "Upravljajte podešavanjima naloga",
      account: "Nalog",
      security: "Bezbjednost",
    },
    start: {
      headerTitle__account: "Nalog",
      headerTitle__security: "Bezbjednost",
      profileSection: {
        title: "Profil",
      },
      usernameSection: {
        title: "Korisničko ime",
        primaryButton__changeUsername: "Promijeni korisničko ime",
        primaryButton__setUsername: "Postavi korisničko ime",
      },
      emailAddressesSection: {
        title: "Email adrese",
        primaryButton: "Dodaj email adresu",
        detailsAction__primary: "Postavi kao osnovno",
        detailsAction__nonPrimary: "Postavi kao osnovno",
        detailsAction__unverified: "Potvrdi",
        destructiveAction: "Ukloni email",
      },
      phoneNumbersSection: {
        title: "Brojevi telefona",
        primaryButton: "Dodaj broj telefona",
        detailsAction__primary: "Postavi kao osnovno",
        detailsAction__nonPrimary: "Postavi kao osnovno",
        detailsAction__unverified: "Potvrdi",
        destructiveAction: "Ukloni broj",
      },
      connectedAccountsSection: {
        title: "Povezani nalozi",
        primaryButton: "Poveži nalog",
        destructiveActionTitle: "Ukloni",
        actionLabel__conectionFailed: "Veza neuspješna — pokušaj ponovo",
        actionLabel__connectionFailed: "Veza neuspješna — pokušaj ponovo",
      },
      passwordSection: {
        title: "Lozinka",
        primaryButton__changePassword: "Promijeni lozinku",
        primaryButton__setPassword: "Postavi lozinku",
      },
      mfaSection: {
        title: "Dvostepena provjera",
        primaryButton: "Dodaj dvostepenu provjeru",
        phoneCode: {
          destructiveActionLabel: "Ukloni",
          actionLabel__setDefault: "Postavi kao osnovno",
        },
        backupCodes: {
          headerTitle: "Rezervni kodovi",
          title__regenerate: "Obnovite rezervne kodove",
          subtitle__regenerate: "Generišite nove rezervne kodove. Stari neće više funkcionisati.",
          actionLabel__regenerate: "Obnovi kodove",
        },
        totp: {
          headerTitle: "Aplikacija za autentifikaciju",
          title: "Aplikacija za autentifikaciju",
          subtitle__removeConnection: "Uklonite aplikaciju za autentifikaciju",
          destructiveActionTitle: "Ukloni",
        },
      },
      dangerSection: {
        title: "Opasno",
        deleteAccountButton: "Obriši nalog",
      },
    },
  },
};
